class Main { 
  public static void main(String[] args) throws ArithmeticException {
    
    // int inty = 10 / 0; 

    // System.out.println("After exception");
    // int x;
    
    // try {
    //   x = 10 / 0; 
    // } catch (ArithmeticException ae) {
    //   System.out.println("Can't divide by zero");
    //   x = 0; 
    // }
    // finally {
    //   System.out.println("I am here at finally");
    // }

    // System.out.println(x);

    // command to manuel create a exception
    // throw 
    // //  your expecting a n error that needs tob ehandle in other needs to be handled somewhere. 

        // throws
  }
}

// fn + F5 is run 
// sysout for System.out.println()